<section class="mt-40">
	<div class="container">
		<div class="col s12">
			<h3>Lista de contatos</h3>
		</div>
		<div class="col s12">
		<?php if(count($dados['contatos'])):  ?>

			<table class="bordered">
		        <thead>
		          <tr>
		              <th>Nome</th>
		              <th>Email</th>
		              <th>Celular</th>
		              <th>Editar</th>
		              <th>Excluir</th>
		          </tr>
		        </thead>
		        
		        <tbody>
		        	<?php 
						foreach($dados['contatos'] as $contato): 
					?>
			          <tr>
			            <td><?php echo $contato->getNome() ?></td>
			            <td><?php echo $contato->getEmail() ?></td>
			            <td><?php echo $contato->getCelular() ?></td>
			            <td>
			            	<a href="/Contato/edit/<?php echo $contato->getContato_id() ?>" class="btn waves-effect waves-light red accent-4" type="button">Editar
	    						<i class="material-icons right">edit</i>
	  						</a>
			            </td>
			            <td>
			            	<button class="btn waves-effect waves-light red accent-4 remove-btn" type="button" data-id="<?php echo $contato->getContato_id() ?>">Remover
	    						<i class="material-icons right">delete_forever</i>
	  						</button>
						</td>
			          </tr>
		            <?php endforeach; ?>
		        </tbody>

		        <tfoot>
		        	<tr>
		        		<td colspan="4"></td>
		        		<td>
		        			<a class="btn waves-effect waves-light red accent-4" href="/Contato/add" >Cadastrar
    							<i class="material-icons right">add</i>
  							</a>
		        		</td>
		        	</tr>
		        </tfoot>
      		</table>
  		<?php else: ?>
			<a class="btn waves-effect waves-light red accent-4" href="/Contato/add" >Cadastrar
				<i class="material-icons right">add</i>
			</a>

		<?php  endif; ?>
		</div>
	</div>
</section>


<script>
	$(document).ready(function(){

		$(".remove-btn").click(function(){
			var id = $(this).data('id');

			$.getJSON("/Contato/delete/"+id, function(txt){
		        if(txt.success) {
		        	location.href="/Contato";
		        }else{
		        	alert(txt.msg);
		        }
		    });
		});

	});
</script>
