<section class="jumbotron pad-section full-h">
	<div class="valign-wrapper full-h">
		<div class="container">
			<div class='col s12 center'>
		 		<img src='/img/LOGO_MATHEUS.png' style="max-width: 200px">	
		 	</div>
			<div class='col s12'>
		 		<h5 class='center full-w mt-40 uptext' style="display: block;" >Simples crud utilizando PHP com MVC, OO e Materializecss</h5>
	 		</div>
		</div>
	</div>
</section>