<html>
	<head lang='en'>
		<meta charset='UTF-8'>
		<title><?php echo ($dados['title']) ? $dados['title'] : "PHP CRUD" ?></title>
		<!-- Compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="/css/app.css">

		<!-- Compiled and minified JavaScript -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	  	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
	</head>
	<body>

	<nav class='header red accent-4'>
		<div class="nav-wrapper">
			<a href="/" class="brand-logo">&nbsp;&nbsp;&nbsp;&nbsp;MATH<strong>CRUD</strong></a>
			<ul class="right">
				<li><a href="/">Home</a></li>
				<li><a href="/Contato">Contato</a></li>
			</ul>
		</div>
	</nav>
	<main>
	